export const API_KEY         = 'MTA0NzM4';
export const CAT_IMAGE_URL   = 'http://thecatapi.com/api/images/get?format=src&type=gif';
export const INCREMENT_COUNT = 'INCREMENT_COUNT';
export const DECREMENT_COUNT = 'DECREMENT_COUNT';
export const FETCH_CAT_DATA_PENDING = 'FETCH_CAT_DATA_PENDING';
export const FETCH_CAT_DATA_SUCCESS = 'FETCH_CAT_DATA_SUCCESS';
export const FETCH_CAT_DATA_FAILED = 'FETCH_CAT_DATA_FAILED'
export const CAT_VOTE_PENDING = 'CAT_VOTE_PENDING';
export const CAT_VOTE_SUCCESS = 'CAT_VOTE_SUCCESS';
export const CAT_VOTE_FAILED = 'CAT_VOTE_FAILED';
